server:
  port: 8004
spring:
  application:
    name: oms-config
  profiles:
    active: native  #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  instance:
    prefer-ip-address:  true
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

